### ISSUE TITLE
Staging - Stopping all processes with SIGTERM

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/ds-mdata-responder#563]
Opened staging logs Monday AM to find a` Stopping all processes with SIGTERM` message. This may be a one-off, but it's first time I've seen this. Last I had tested staging was on a Friday.

````
2016-08-07T23:10:48.146944+00:00 app[web.1]: { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
2016-08-07T23:10:48.148549+00:00 app[web.1]: js-bson: Failed to load c++ bson extension, using pure JS version
2016-08-07T23:10:51.695171+00:00 app[web.1]: Mongoose connected to connectionConfig with status code: 1
2016-08-07T23:10:51.882712+00:00 app[web.1]: [32minfo[39m: Express server listening on port 44196 in thor mode...
2016-08-07T23:12:49.617551+00:00 heroku[web.1]: Stopping all processes with SIGTERM
````

What's also new and perhaps unrelated, is that after restarting the dynos on staging and testing a reportback, the log shows some errors I haven't seen yet. They look related to the bit.ly integration... the reportback was submitted correctly: https://thor.dosomething.org/reportback/170709%3Ffid%3D235749

````
2016-08-08T15:40:14.863319+00:00 app[web.1]: [34mdebug[39m: phoenix.onCampaignsReportback body: ["170709"]
2016-08-08T15:40:14.863719+00:00 app[web.1]: [32minfo[39m: reportback.reportbackToDS:https://thor.dosomething.org/reportback/170709
2016-08-08T15:40:14.964214+00:00 app[web.1]: <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
2016-08-08T15:40:14.964223+00:00 app[web.1]:   <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
2016-08-08T15:40:14.964230+00:00 app[web.1]:   <link rel="stylesheet" href="/cdn/maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" />
2016-08-08T15:40:14.964237+00:00 app[web.1]:           <div class="col-sm-10 col-sm-offset-1">
2016-08-08T15:40:14.964237+00:00 app[web.1]:             <div class="error-message-container">
2016-08-08T15:40:14.964243+00:00 app[web.1]:                     <div class="widget-main">
2016-08-08T15:40:14.964249+00:00 app[web.1]:           </div>
2016-08-08T15:40:14.964254+00:00 app[web.1]:         <a href="/help/whats_new">What's New</a> |
2016-08-08T15:40:14.964266+00:00 app[web.1]:     at shortenLinkAndUpdateMCProfile (/app/app/lib/reportback/index.js:420:5)
2016-08-08T15:40:12.134314+00:00 heroku[router]: at=info method=POST path="/reportback/heisenberg" host=ds-mdata-responder-staging.herokuapp.com request_id=d33c276f-81f9-47e3-a14f-153a316fd407 fwd="64.22.127.230" dyno=web.1 connect=0ms service=22ms status=200 bytes=117
2016-08-08T15:40:14.964259+00:00 app[web.1]: </body>
2016-08-08T15:40:14.964260+00:00 app[web.1]:  | stack: Error
2016-08-08T15:40:14.964261+00:00 app[web.1]:     at /app/app/lib/reportback/index.js:440:23
2016-08-08T15:40:14.964266+00:00 app[web.1]:     at shortenLinkAndUpdateMCProfile (/app/app/lib/reportback/index.js:420:5)
2016-08-08T15:40:14.964267+00:00 app[web.1]:     at _fulfilled (/app/node_modules/q/q.js:834:54)
2016-08-08T15:40:14.964267+00:00 app[web.1]:     at self.promiseDispatch.done (/app/node_modules/q/q.js:863:30)
2016-08-08T15:40:14.977359+00:00 app[web.1]: [32minfo[39m: mobilecommons.optin success oip:210199 user:17322416750
2016-08-08T15:40:12.134314+00:00 heroku[router]: at=info method=POST path="/reportback/heisenberg" host=ds-mdata-responder-staging.herokuapp.com request_id=d33c276f-81f9-47e3-a14f-153a316fd407 fwd="64.22.127.230" dyno=web.1 connect=0ms service=22ms status=200 bytes=117
2016-08-08T15:40:14.964259+00:00 app[web.1]: </body>
2016-08-08T15:40:14.964259+00:00 app[web.1]: </html>
2016-08-08T15:40:14.964266+00:00 app[web.1]:     at shortenLinkAndUpdateMCProfile (/app/app/lib/reportback/index.js:420:5)
2016-08-08T15:40:14.964267+00:00 app[web.1]:     at _fulfilled (/app/node_modules/q/q.js:834:54)
2016-08-08T15:40:14.977359+00:00 app[web.1]: [32minfo[39m: mobilecommons.optin success oip:210199 user:17322416750
2016-08-08T15:40:14.964259+00:00 app[web.1]: </body>
2016-08-08T15:40:14.964261+00:00 app[web.1]:     at Object.exports.optout (/app/mobilecommons/mobilecommons.js:209:15)
2016-08-08T15:40:14.964262+00:00 app[web.1]:     at shortenLink (/app/app/lib/bitly/bitly.js:24:5)
2016-08-08T15:40:14.964267+00:00 app[web.1]:     at self.promiseDispatch.done (/app/node_modules/q/q.js:863:30)
2016-08-08T15:40:14.977359+00:00 app[web.1]: [32minfo[39m: mobilecommons.optin success oip:210199 user:17322416750
2016-08-08T15:40:14.964259+00:00 app[web.1]: </body>
2016-08-08T15:40:14.964261+00:00 app[web.1]:     at Object.exports.optout (/app/mobilecommons/mobilecommons.js:209:15)
2016-08-08T15:40:14.964261+00:00 app[web.1]:     at /app/app/lib/reportback/index.js:440:23
2016-08-08T15:40:14.964267+00:00 app[web.1]:     at _fulfilled (/app/node_modules/q/q.js:834:54)
2016-08-08T15:40:14.964267+00:00 app[web.1]:     at self.promiseDispatch.done (/app/node_modules/q/q.js:863:30)
2016-08-08T15:40:14.977359+00:00 app[web.1]: [32minfo[39m: mobilecommons.optin success oip:210199 user:17322416750
2016-08-08T15:40:12.134314+00:00 heroku[router]: at=info method=POST path="/reportback/heisenberg" host=ds-mdata-responder-staging.herokuapp.com request_id=d33c276f-81f9-47e3-a14f-153a316fd407 fwd="64.22.127.230" dyno=web.1 connect=0ms service=22ms status=200 bytes=117
2016-08-08T15:40:14.964259+00:00 app[web.1]: </body>
2016-08-08T15:40:14.964259+00:00 app[web.1]: </html>
````

**Comment by aaronschachter** [comment]
2nd submission is still outputting HTML:
````
2016-08-08T15:54:21.687620+00:00 app[web.1]: [32minfo[39m: reportback.reportbackToDS:https://thor.dosomething.org/reportback/170709
2016-08-08T15:54:21.758034+00:00 app[web.1]: [32minfo[39m: mobilecommons.optin success oip:210199 user:17322416750
2016-08-08T15:54:21.767518+00:00 app[web.1]:        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
2016-08-08T15:54:21.767519+00:00 app[web.1]: <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
2016-08-08T15:54:21.767519+00:00 app[web.1]: <head>
2016-08-08T15:54:21.767520+00:00 app[web.1]:   <meta charset="utf-8">
2016-08-08T15:54:21.767523+00:00 app[web.1]:   <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
2016-08-08T15:54:21.767527+00:00 app[web.1]:   <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
2016-08-08T15:54:21.767528+00:00 app[web.1]:   <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
2016-08-08T15:54:21.767532+00:00 app[web.1]: 
2016-08-08T15:54:21.767532+00:00 app[web.1]: </head>
2016-08-08T15:54:21.767536+00:00 app[web.1]:               </div>
2016-08-08T15:54:21.767536+00:00 app[web.1]: 
2016-08-08T15:54:21.767537+00:00 app[web.1]:               <div class="position-relative">
2016-08-08T15:54:21.767537+00:00 app[web.1]:                 <div id="login-box" class="login-box visible widget-box no-border">
2016-08-08T15:54:21.767538+00:00 app[web.1]:                     <div class="widget-main">
2016-08-08T15:54:21.767549+00:00 app[web.1]:                   </div>
2016-08-08T15:54:21.767552+00:00 app[web.1]: 
2016-08-08T15:54:21.767556+00:00 app[web.1]:       </p>
2016-08-08T15:54:21.767557+00:00 app[web.1]: </html>
2016-08-08T15:54:21.767563+00:00 app[web.1]:     at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:796:13)
2016-08-08T15:54:19.998663+00:00 heroku[router]: at=info method=POST path="/reportback/heisenberg" host=ds-mdata-responder-staging.herokuapp.com request_id=c5af59b1-ecf9-4f69-a3ae-d6e187d72c58 fwd="64.22.127.230" dyno=web.1 connect=1ms service=9ms status=200 bytes=117
2016-08-08T15:54:21.767558+00:00 app[web.1]:     at /app/app/lib/reportback/index.js:440:23
2016-08-08T15:54:21.767564+00:00 app[web.1]:     at flush (/app/node_modules/q/q.js:125:13)
2016-08-08T15:54:21.767565+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:67:7)
2016-08-08T15:54:21.767562+00:00 app[web.1]:     at _fulfilled (/app/node_modules/q/q.js:834:54)
2016-08-08T15:54:21.767563+00:00 app[web.1]:     at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:796:13)
````

I'm testing the most recent commit to `dev`: 93bc41a, Heroku v63

**Comment by aaronschachter** [comment]
The `Stopping all processes with SIGTERM` message is a mystery, but all of the errors coming back as HTML stem from a password change to our MoCo admin account. Closing for now.
